micronaut:
  application:
    name: servicing
  server:
    port: 7780
datasources:
  default:
    url: jdbc:oracle:thin:@localhost:1521/xe
    driverClassName: oracle.jdbc.OracleDriver
    username: system
    password: oracle
    schema-generate: CREATE_DROP
    dialect: ORACLE
jpa.default.properties.hibernate.hbm2ddl.auto: update
